# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gCedaAxr4A0rFWuXG3yO0vs5emMZGuY9
"""

from google.colab import files
uploaded = files.upload()

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import matplotlib.pyplot as plt

file_name = 'API_SP.POP.TOTL_DS2_en_csv_v2_38144.csv'
data = pd.read_csv(file_name, skiprows=4)

print("Preview of dataset:")
print(data.head())

india = data[data['Country Name'] == 'India']

population_data = india.loc[:, '1960':'2024'].transpose()
population_data.columns = ['Population']

population_data.index.name = 'Year'
population_data.reset_index(inplace=True)

population_data['Population (Millions)'] = population_data['Population'] / 1_000_000

plt.figure(figsize=(14, 6))
plt.bar(population_data['Year'], population_data['Population (Millions)'], color='skyblue')
plt.title("India's Population Growth (1960 to 2024)", fontsize=16)
plt.xlabel("Year")
plt.ylabel("Population (in millions)")
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

data = pd.DataFrame({
    'Name': ['Aakash', 'Meena', 'Rohan', 'Shruti', 'Amit', 'Divya', 'Zara'],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Female'],
    'Age': [21, 19, 23, 22, 24, 20, 22]
})

gender_counts = data['Gender'].value_counts()

# Plot a bar chart
plt.figure(figsize=(6, 4))
plt.bar(gender_counts.index, gender_counts.values, color=['skyblue', 'lightpink'])
plt.title('Gender Distribution')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

# Plot a histogram for Age
plt.figure(figsize=(7, 5))
plt.hist(data['Age'], bins=5, color='lightgreen', edgecolor='black')
plt.title('Age Distribution')
plt.xlabel('Age')
plt.ylabel('Number of Students')
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()